language: node_js
node_js:
  - '12'
git:
  depth: 3
notifications:
  email:
    recipients:
      - me@carlosvldz.com
      - carlosvldz@outlook.com
    on_success: always
    on_failure: always
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: 'Deploy del proyecto'
  on:
    branch: master
